### ISSUE TITLE
BUG helm chart will install but not uninstall or update

### ISSUE THREAD

**Issue by Heiko-san** [clastix/kamaji-etcd#41] opened 2023-08-21 14:13 UTC
Hi,

we created an additional datastore of type etcd using your helm chart clastix/kamaji-etcd. It successfully installs, but as soon as you try to update or delete the datastore / the helm chart, you get the following error:

```
helm upgrade kamaji-etcd-2 clastix/kamaji-etcd -n kamaji-etcd-2 -f values.yaml
Error: UPGRADE FAILED: post-upgrade hooks failed: admission webhook "vdatastore.kb.io" denied the request: unable to decode into *v1alpha1.DataStore: there is no content to decode
```

Actually it seems (most?) resources get updated. However you also get the error, if you try to `kubectl delete datastores.kamaji.clastix.io kamaji-etcd-2`, resulting in an half-installed datastore. It doesn't entirely get removed.

We use kamaji v0.3.3 together with cluster-api v1.5.0 with infrastructure-vsphere v1.7.0 and your kamaji plugin control-plane-kamaji v0.3.0.

**Comment by prometherion** [comment] 2023-08-21 14:55
This is a duplicate of #38, if you don't mind I'd close this since we already have an open PR to address it: please, let me know!

**Closed** 2023-08-24 09:05 UTC
Labels: duplicate
